# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "unirennes-slides"
version = "0.2.0"
entrypoint = "src/lib.typ"
authors = ["Augustin Godinot <augustin.godinot@inria.fr"]
license = "Unlicense"
description = "Unofficial Typst template to create slides using Université de Rennes charter"
# homepage = ""
repository = "https://github.com/grodino/unirennes-slides-typst"
# keywords = []
# categories = []
# disciplines = []
exclude = [".github", "docs", "scripts", "tests", ".typstignore", "Justfile"]

[template]
path = "template"
entrypoint = "main.typ"
